version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/openjdk:jdk-node-browsers
    working_directory: /tmp

jobs:
  install:
    executor: my-executor

    steps:
      - checkout:
          path: workspace
      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "workspace/yarn.lock" }}
            - v1-node-{{ arch }}-{{ .Branch }}-
            - v1-node-{{ arch }}-
      - run:
          name: Nodejs Version
          command: node --version
      - run:
          name: Install Packages
          command: cd workspace && yarn install --frozen-lockfile
      - save_cache:
          name: Save node_modules cache
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "workspace/yarn.lock" }}
          paths:
            - facebook-www
            - node_modules
      - persist_to_workspace:
          root: workspace
          paths:
            - .

workflows:
  validate:
    jobs:
      - install
