version: 2
jobs:
  build:

    docker:
      - image: circleci/openjdk:8-jdk-node-browsers

    parallelism: 1

    steps:
      - checkout

      - run: echo $CIRCLE_COMPARE_URL | cut -d/ -f7

      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-node-{{ arch }}-{{ .Branch }}-
            - v1-node-{{ arch }}-

      - run:
          name: Nodejs Version
          command: node --version

      - run:
          name: Install Packages
          command: yarn install --frozen-lockfile

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Check Prettier
          command: yarn lightyear:prettier-check

      - run:
          name: Test
          command: yarn test

      - run:
          name: Test Prod
          command: yarn test-prod

      - run:
          name: Check that build succeeds
          command: yarn lightyear:build

      - save_cache:
          name: Save node_modules cache
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
